In [87]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import networkx as nx
import json
import numpy as np


In [91]:
# Create a List to parse the Netlist 
cir = []

with open('net.txt') as f:
    lines = f.readlines() # list containing lines of file
    for line in lines:
        line = line.strip() # remove leading/trailing white spaces
        data = [item.strip() for item in line.split(' ')] #extract purse data     
        cir.append(data) # append it to cir


# Create a directed graph Gd
G_d = nx.DiGraph()
branches = len(cir) #number of Branches 
Y = np.zeros((branches,branches))
# Create Aa and Y

for item in cir:
    i = int(item[1])
    j = int(item[2])
    # Create Aa
    G_d.add_edge(i,j)
    # Generate Add. Matrix
    if('R' in item[0]):
        Y[i,j] = (1/int(item[3]))
    elif('I'in item[0]):
        Y[i,j] = (1/int(item[3]))
    else:
        print('Error')



[[0.  0.  0.  0.1 0.  0. ]
 [0.1 0.  0.1 0.1 0.  0. ]
 [0.  0.  0.  0.1 0.  0. ]
 [0.1 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]]


In [89]:
A = nx.incidence_matrix(G_d,oriented=True).todense()
print(A)




[[-1. -1. -1.  0.  0.  0.]
 [ 1.  0.  0. -1.  0.  1.]
 [ 0.  1.  0.  0. -1.  0.]
 [ 0.  0.  1.  1.  1. -1.]]
